server:
  port: 8083

spring:
  application:
      name: AirPollutionService
  data:
    mongodb:
        uri: mongodb+srv://ashishkatkar1:RK5IbAHMmuXZqx1F@cluster0.q9seg.mongodb.net/AirPollutionService?retryWrites=true&w=majority

data:
  exception:
     dataExists: Data Already Exist..!!
     dataNotFound: Data Not Found..!!

eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/
     
jwt:
  secret: secrectkey123