server:
    port: 8080
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: APIGatewayForService
 cloud:
    gateway:
      routes:
      - id: AdminService
        uri: http://localhost:8083/
        predicates:
        - Path=/api/v1/**
      - id: JwtService
        uri: http://localhost:8081/
        predicates:
        - Path=/api/jwt/**
      - id: AirPollutionServices
        uri: http://localhost:8088/
        predicates:
        - Path=/api/user/**
          
      
  